FROM python:3.13-slim-bookworm
RUN apt-get update && apt-get install -y build-essential libpq-dev && rm -rf /var/lib/apt/lists/*
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --frozen --no-install-project --no-dev

WORKDIR /app

COPY api_build ./api_build
RUN touch README.md

EXPOSE 8080

ENTRYPOINT [ "uv", "run", "fastapi", "run", "api_build/app.py", "--port", "8080" ]